-- MySQL Script generated by MySQL Workbench
-- Thu May 16 11:20:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema equipamientoti
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `equipamientoti` ;

-- -----------------------------------------------------
-- Schema equipamientoti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equipamientoti` DEFAULT CHARACTER SET utf8 ;
USE `equipamientoti` ;

-- -----------------------------------------------------
-- Table `equipamientoti`.`Unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`Unidad` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`Unidad` (
  `UnidadId` INT NOT NULL AUTO_INCREMENT,
  `NombreUnidad` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`UnidadId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`Ciudad` (
  `CiudadId` INT NOT NULL AUTO_INCREMENT,
  `NombreCiudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CiudadId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`Oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`Oficina` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`Oficina` (
  `LocacionId` INT NOT NULL AUTO_INCREMENT,
  `Calle` VARCHAR(45) NOT NULL,
  `NumeroCalle` VARCHAR(45) NOT NULL,
  `CiudadId` INT NOT NULL,
  PRIMARY KEY (`LocacionId`),
  INDEX `fk_Locacion_Ciudad1_idx` (`CiudadId` ASC),
  CONSTRAINT `fk_Locacion_Ciudad1`
    FOREIGN KEY (`CiudadId`)
    REFERENCES `equipamientoti`.`Ciudad` (`CiudadId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`Funcionario` (
  `UsuarioId` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(150) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NOT NULL,
  `SegundoNombre` VARCHAR(45) NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `UnidadId` INT NOT NULL,
  `LocacionId` INT NOT NULL,
  PRIMARY KEY (`UsuarioId`, `UnidadId`, `LocacionId`),
  INDEX `fk_Funcionario_Unidad1_idx` (`UnidadId` ASC),
  INDEX `fk_Funcionario_Locacion1_idx` (`LocacionId` ASC),
  CONSTRAINT `fk_Funcionario_Unidad1`
    FOREIGN KEY (`UnidadId`)
    REFERENCES `equipamientoti`.`Unidad` (`UnidadId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Locacion1`
    FOREIGN KEY (`LocacionId`)
    REFERENCES `equipamientoti`.`Oficina` (`LocacionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`Documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`Documento` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`Documento` (
  `DocumentoId` INT NOT NULL AUTO_INCREMENT,
  `UsuarioId` INT NOT NULL,
  `DepartamentoId` INT NOT NULL,
  `FechaEntrega` DATE NOT NULL,
  `FechaDevolucion` DATE NULL,
  `Observaciones` VARCHAR(65) NULL,
  `MotivoEntrega` VARCHAR(65) NOT NULL,
  `Motivodevolucion` VARCHAR(65) NULL,
  `UrlDocumento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DocumentoId`),
  INDEX `fk_Documento_Funcionario1_idx` (`UsuarioId` ASC, `DepartamentoId` ASC),
  CONSTRAINT `fk_Documento_Funcionario1`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `equipamientoti`.`Funcionario` (`UsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`Marca` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`Marca` (
  `MarcaId` INT NOT NULL AUTO_INCREMENT,
  `NombreMarca` VARCHAR(45) NOT NULL,
  `Descipcion` VARCHAR(45) NULL,
  PRIMARY KEY (`MarcaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`TipoEquipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`TipoEquipo` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`TipoEquipo` (
  `TipoEquipoId` INT NOT NULL AUTO_INCREMENT,
  `NombreTipo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`TipoEquipoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`Equipo` (
  `EquipoId` INT NOT NULL AUTO_INCREMENT,
  `Serial` VARCHAR(45) NOT NULL,
  `CodigoInterno` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `MarcaId` INT NOT NULL,
  `TipoEquipoId` INT NOT NULL,
  PRIMARY KEY (`EquipoId`, `MarcaId`, `TipoEquipoId`),
  INDEX `fk_Equipo_Marca1_idx` (`MarcaId` ASC),
  INDEX `fk_Equipo_TipoEquipo1_idx` (`TipoEquipoId` ASC),
  CONSTRAINT `fk_Equipo_Marca1`
    FOREIGN KEY (`MarcaId`)
    REFERENCES `equipamientoti`.`Marca` (`MarcaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_TipoEquipo1`
    FOREIGN KEY (`TipoEquipoId`)
    REFERENCES `equipamientoti`.`TipoEquipo` (`TipoEquipoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipamientoti`.`EquipoDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamientoti`.`EquipoDocumento` ;

CREATE TABLE IF NOT EXISTS `equipamientoti`.`EquipoDocumento` (
  `EquipoId` INT NOT NULL,
  `MarcaId` INT NOT NULL,
  `TipoEquipoId` INT NOT NULL,
  `DocumentoId` INT NOT NULL,
  PRIMARY KEY (`EquipoId`, `MarcaId`, `TipoEquipoId`, `DocumentoId`),
  INDEX `fk_Equipo_has_Documento_Documento1_idx` (`DocumentoId` ASC),
  INDEX `fk_Equipo_has_Documento_Equipo1_idx` (`EquipoId` ASC, `MarcaId` ASC, `TipoEquipoId` ASC),
  CONSTRAINT `fk_Equipo_has_Documento_Equipo1`
    FOREIGN KEY (`EquipoId` , `MarcaId` , `TipoEquipoId`)
    REFERENCES `equipamientoti`.`Equipo` (`EquipoId` , `MarcaId` , `TipoEquipoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_has_Documento_Documento1`
    FOREIGN KEY (`DocumentoId`)
    REFERENCES `equipamientoti`.`Documento` (`DocumentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
